# Generated by Django 2.2.1 on 2019-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon', '0002_auto_20190509_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
