# Generated by Django 2.2.1 on 2019-05-10 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dragon', '0003_pattern_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_for', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='dragon.Pattern')),
                ('voter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
